---
.travis.yml:
  script:
    - bundle exec rake validate
    - bundle exec rake lint
    - bundle exec rake spec SPEC_OPTS='--format documentation'
    - bundle exec rake metadata
  forge_login: "camptocamp"
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" PARSER="future"
  allow_failures:
  - env: PUPPET_GEM_VERSION="~> 3.0" PARSER="future"
Gemfile:
  required:
  - gem: rake
  - gem: rspec-puppet
    git: "https://github.com/rodjek/rspec-puppet.git"
  - gem: puppetlabs_spec_helper
  - gem: puppet-lint
  - gem: metadata-json-lint
Rakefile:
  default_disabled_lint_checks:
  - 'disable_80chars'
