---
.travis.yml:
  script: "\"bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'\""
  after_success:
    # Publish modules to the Forge automatically
    - "git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng"
    - ".forge-releng/publish"
  publisher_login: "camptocamp"
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 2.7"
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
Gemfile:
  required:
  - gem: rake
  - gem: rspec-puppet
  - gem: puppetlabs_spec_helper
  - gem: puppet-lint
  - gem: pry
  - gem: simplecov
Rakefile:
  default_disabled_lint_checks:
  - 'disable_80chars'
