---
.travis.yml:
  use_containers: true
  script:
    - bundle exec rake validate
    - bundle exec rake lint
    - bundle exec rake spec SPEC_OPTS='--format documentation'
    - bundle exec rake metadata
  forge_login: "camptocamp"
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rake
      - gem: rspec
        version: '< 3.2'
        condition: 'RUBY_VERSION =~ /^1.8/'
      - gem: rspec-puppet
      - gem: puppetlabs_spec_helper
      - gem: metadata-json-lint
      - gem: puppet-lint
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-empty_string-check
      - gem: puppet-lint-spaceship_operator_without_tag-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-undef_in_function-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-file_ensure-check
      - gem: puppet-lint-fileserver-check
      - gem: puppet-lint-version_comparison-check
      - gem: rspec-puppet-facts
    ':system_tests':
      - gem: beaker
      - gem: beaker-rspec
      - gem: serverspec
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
