---
.travis.yml:
  script:
    - bundle exec rake validate
    - bundle exec rake lint
    - bundle exec fakeroot rake spec SPEC_OPTS='--format documentation'
    - bundle exec rake metadata
  forge_login: "camptocamp"
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  allow_failures:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
Gemfile:
  required:
  - gem: rake
  - gem: rspec-puppet
    git: "https://github.com/camptocamp/rspec-puppet.git"
    # Until https://github.com/rodjek/rspec-puppet/pull/222 is merged
    branch: "future-no-import"
  - gem: puppetlabs_spec_helper
  - gem: puppet-lint
  - gem: metadata-json-lint
  - gem: puppet_facts
    git: "https://github.com/camptocamp/puppet_facts.git"
Rakefile:
  default_disabled_lint_checks:
  - 'disable_80chars'
