---
.travis.yml:
  use_containers: true
  script:
    - bundle exec rake validate
    - bundle exec rake lint
    - bundle exec rake spec SPEC_OPTS='--format documentation'
  forge_login: "camptocamp"
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rake
        version: ' < 11.0'
        condition: 'RUBY_VERSION =~ /^1\.8/'
      - gem: rspec
        version: '< 3.2'
        condition: 'RUBY_VERSION =~ /^1\.8/'
      - gem: rspec-puppet
      - gem: puppetlabs_spec_helper
      - gem: metadata-json-lint
      - gem: puppet-lint
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-empty_string-check
      - gem: puppet-lint-spaceship_operator_without_tag-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-undef_in_function-check
      - gem: puppet-lint-leading_zero-check
      - gem: puppet-lint-trailing_comma-check
      - gem: puppet-lint-file_ensure-check
      - gem: puppet-lint-version_comparison-check
      - gem: puppet-lint-fileserver-check
      - gem: puppet-lint-file_source_rights-check
      - gem: puppet-lint-alias-check
      - gem: rspec-puppet-facts
      - gem: ruby-augeas
      - gem: github_changelog_generator
        condition: 'RUBY_VERSION !~ /^1\.8/'
      - gem: puppet-blacksmith
        condition: 'RUBY_VERSION !~ /^1\./'
    ':system_tests':
      - gem: beaker
      - gem: beaker-rspec
      - gem: beaker_spec_helper
      - gem: serverspec
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
#spec/acceptance/nodesets/centos-5-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/centos-6-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/centos-6-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/centos-6-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/centos-7-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/centos-7-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/centos-7-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/debian-6-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/debian-6-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/debian-6-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/debian-7-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/debian-7-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/debian-7-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/debian-8-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/debian-8-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/debian-8-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-12.04-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-12.04-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-12.04-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-14.04-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-14.04-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-14.04-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-14.10-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-14.10-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-14.10-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-15.04-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-15.04-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-15.04-x86_64-docker.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-15.10-x86_64-openstack.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-15.10-x86_64-vagrant.yml:
#  delete: true
#spec/acceptance/nodesets/ubuntu-15.10-x86_64-docker.yml:
#  delete: true
