---
.travis.yml:
  use_containers: true
  script:
    - bundle exec rake validate
    - bundle exec rake lint
    - bundle exec rake spec SPEC_OPTS='--format documentation'
    - bundle exec rake metadata
  forge_login: "camptocamp"
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0" FACTER_GEM_VERSION="~> 1.7.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0"
  allow_failures:
  - rvm: 2.0.0
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rake
      - gem: rspec-puppet
        git: https://github.com/rodjek/rspec-puppet.git
      - gem: puppetlabs_spec_helper
      - gem: puppet-lint
        version: '~> 1.0.0'
      - gem: puppet-lint-unquoted_string-check
      - gem: puppet-lint-empty_string-check
      - gem: puppet-lint-spaceship_operator_without_tag-check
      - gem: puppet-lint-variable_contains_upcase
      - gem: puppet-lint-absolute_classname-check
      - gem: puppet-lint-undef_in_function-check
      - gem: simplecov
      - gem: rspec-puppet-facts
      - gem: json
      - gem: metadata-json-lint
    ':system_tests':
      - gem: beaker
        git: https://github.com/mcanevet/beaker
        branch: openstack
      - gem: beaker-rspec
      - gem: serverspec
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
