---
language: ruby
bundler_args: --without development
script: <%= @configs['script'] %>
<% if @configs['after_success'] -%>
after_success:
  <%= @configs['after_success'] %>
<% end -%>
<% if @configs['publisher_login'] -%>
env:
  global:
    - PUBLISHER_LOGIN=<%= @configs['publisher_login'] %>
  <%- if @configs['secure_global_env'] -%>
    <%- @configs['secure_global_env'].each do |s| -%>
    - secure: "<%= s %>"
    <%- end -%>
  <%- end -%>
<%- end -%>
matrix:
  fast_finish: true
  include:
<% @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end -%>
<% if @configs['extras'] -%>
<%   @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
    env: <%= extra['env'] %>
<%   end -%>
<% end -%>
notifications:
  email: false
