---
language: ruby
<% if @configs['use_containers'] -%>
sudo: false
cache: bundler
<% end -%>
bundler_args: '$([ -z "${BEAKER_set}" ] && echo "--without system_tests")'
before_install:
  - ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
<% if @configs['install'] -%>
install: <%= @configs['install'] %>
<% end -%>
script: <%= @configs['script'] %>
<% if @configs['after_success'] -%>
after_success:
  <%= @configs['after_success'] %>
<% end -%>
matrix:
  fast_finish: true
  include:
<% @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end -%>
<% if @configs['extras'] -%>
<%   @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
    env: <%= extra['env'] %>
<%   end -%>
<% end -%>
<% if @configs['allow_failures'] -%>
  allow_failures:
<%- @configs['allow_failures'].each do |allow| -%>
    - rvm: <%= allow['rvm'] %>
      env: <%= allow['env'] %>
<%   end -%>
<% end -%>
notifications:
  email: false
<% if @configs['forge_password'] -%>
deploy:
  provider: puppetforge
  user: <%= @configs['forge_login'] %>
  password:
    secure: "<%= @configs['forge_password'] %>"
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
<% end -%>
<% if @configs['globals'] -%>
env:
  global:
<%- @configs['globals'].each do |envs| -%>
<%- envs.each do |k, v| -%>
    - <%= k %>: <%= v %>
<% end -%>
<% end -%>
<% end -%>
