---
language: ruby
<% if @configs['use_containers'] -%>
sudo: false
cache: bundler
<% end -%>
bundler_args: --without system_tests
<% if @configs['install'] -%>
install: <%= @configs['install'] %>
<% end -%>
script: <%= @configs['script'] %>
<% if @configs['after_success'] -%>
after_success:
  <%= @configs['after_success'] %>
<% end -%>
matrix:
  fast_finish: true
  include:
<% @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end -%>
<% if @configs['extras']
     @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
    env: <%= extra['env'] %>
<%     if extra.has_key?('bundler_args') -%>
    bundler_args: <%= extra['bundler_args'] %>
<%     end -%>
<%     if extra.has_key?('script') -%>
    script: <%= extra['script'] %>
<%     end
     end
   end -%>
<% if File.file?("modules/#{@configs[:puppet_module]}/metadata.json")
     require 'json'
     metadata = JSON.parse(File.read("modules/#{@configs[:puppet_module]}/metadata.json"))
     if ! metadata['operatingsystem_support'].nil?
       metadata['operatingsystem_support'].each do |os_sup|
         operatingsystem = os_sup['operatingsystem'].downcase
           os_sup['operatingsystemrelease'].map do |operatingsystemmajrelease|
           if @configs['acceptance']
             @configs['acceptance'].each do |spec| -%>
  - env: BEAKER_set="<%= operatingsystem %>-<%= operatingsystemmajrelease %>-x86_64-openstack"
    bundler_args:
    script: '[ -z "${OS_AUTH_URL}" -o -z "${OS_USERNAME}" -o -z "${OS_PASSWORD}" -o -z "${OS_TENANT_NAME}" ] || bundle exec rspec spec/acceptance/<%= spec %>_spec.rb'
<%        end
        end
      end
    end
  end
end -%>
<% if @configs['allow_failures'] -%>
  allow_failures:
<%- @configs['allow_failures'].each do |allow| -%>
    - rvm: <%= allow['rvm'] %>
      env: <%= allow['env'] %>
<%   end -%>
<% end -%>
notifications:
  email: false
<% if @configs['forge_password'] -%>
deploy:
  provider: puppetforge
  user: <%= @configs['forge_login'] %>
  password:
    secure: "<%= @configs['forge_password'] %>"
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
<% end -%>
<% if @configs['globals'] -%>
env:
  global:
<%- @configs['globals'].each do |envs| -%>
<%- envs.each do |k, v| -%>
    - <%= k %>: <%= v %>
<% end -%>
<% end -%>
<% end -%>
