---
language: ruby
<% if @configs['use_containers'] -%>
sudo: false
addons:
  apt:
    packages:
      - libaugeas-dev
    sources:
      - augeas
cache: bundler
<% end -%>
bundler_args: --without system_tests
<% if @configs['install'] -%>
install: <%= @configs['install'] %>
<% end -%>
script: <%= @configs['script'] %>
<% if @configs['after_success'] -%>
after_success:
  <%= @configs['after_success'] %>
<% end -%>
matrix:
  fast_finish: true
  include:
<% require 'octokit'
begin
  Octokit::Client.new(:netrc => true).repo "camptocamp/#{@configs[:puppet_module]}"
  @configs['includes'].each do |include| -%>
  - rvm: <%= include['rvm'] %>
    env: <%= include['env'] %>
<% end
rescue Octokit::NotFound -%>
  - rvm: 2.1.10
    env: PUPPET_GEM_VERSION="~> 4.0"
<% end -%>
<% if @configs['extras']
     @configs['extras'].each do |extra| -%>
  - rvm: <%= extra['rvm'] %>
<%     if extra.has_key?('sudo') -%>
    sudo: <%= extra['sudo'] %>
<%     end -%>
<%     if extra.has_key?('services') -%>
    services: <%= extra['services'] %>
<%     end -%>
    env: <%= extra['env'] %>
<%     if extra.has_key?('bundler_args') -%>
    bundler_args: <%= extra['bundler_args'] %>
<%     end -%>
<%     if extra.has_key?('script') -%>
    script: <%= extra['script'] %>
<%     end
     end
   end -%>
<% if File.file?("modules/#{@configs[:puppet_module]}/metadata.json")
     require 'json'
     metadata = JSON.parse(File.read("modules/#{@configs[:puppet_module]}/metadata.json"))
     if ! metadata['operatingsystem_support'].nil?
       operatingsystem_support = metadata['operatingsystem_support'].map { |o|
         o['operatingsystem'] = 'CentOS' if ['redhat', 'oraclelinux', 'scientific', 'amazon'].include? o['operatingsystem'].downcase
         o
       }.uniq
       operatingsystem_support.each do |os_sup|
         operatingsystem = os_sup['operatingsystem'].downcase
           os_sup['operatingsystemrelease'].map do |operatingsystemmajrelease|
           if @configs['acceptance']
             @configs['acceptance'].each do |spec| -%>
  - rvm: default
    sudo: required
    dist: trusty
    services: docker
    env: BEAKER_set="<%= operatingsystem %>-<%= operatingsystemmajrelease %>"
    bundler_args:
    script: sudo service docker restart ; sleep 10 && bundle exec rspec spec/acceptance/<%= spec %>_spec.rb
<%        end
        end
      end
    end
  end
end -%>
<% if @configs['allow_failures'] -%>
  allow_failures:
<%- @configs['allow_failures'].each do |allow| -%>
    - rvm: <%= allow['rvm'] %>
      env: <%= allow['env'] %>
<%   end -%>
<% end -%>
notifications:
  email: false
<% if @configs['forge_password'] -%>
deploy:
  provider: puppetforge
  user: <%= @configs['forge_login'] %>
  password:
    secure: "<%= @configs['forge_password'] %>"
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 2.1.9
<% end -%>
<% if @configs['globals'] -%>
env:
  global:
<%- @configs['globals'].each do |envs| -%>
<%- envs.each do |k, v| -%>
    - <%= k %>: <%= v %>
<% end -%>
<% end -%>
<% end -%>
<% if @configs['branches'] -%>
branches:
  only:
<% @configs['branches'].each do |branch| -%>
    - <%= branch %>
<% end -%>
<% end -%>
